# Generated by Django 5.1.5 on 2026-07-15 02:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chats", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("TEXT", "Text"),
                            ("IMAGE", "Image"),
                            ("SYSTEM", "System"),
                        ],
                        default="TEXT",
                        max_length=10,
                    ),
                ),
                ("text_content", models.TextField(blank=True, default="")),
                ("media_url", models.URLField(blank=True, default="", max_length=512)),
                (
                    "media_visibility",
                    models.CharField(
                        choices=[("NORMAL", "Normal"), ("VIEW_ONCE", "View once")],
                        default="NORMAL",
                        max_length=10,
                    ),
                ),
                ("viewed_at", models.DateTimeField(blank=True, null=True)),
                ("media_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "media_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("VIEWED", "Viewed"),
                            ("EXPIRED", "Expired"),
                            ("DELETED", "Deleted"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chats.chat",
                    ),
                ),
                (
                    "reply_to_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replies",
                        to="messaging.message",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "db_table": "messages",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["chat", "created_at"], name="idx_message_chat_created"
                    ),
                    models.Index(
                        fields=["media_status", "media_expires_at"],
                        name="idx_message_media_expiry",
                    ),
                ],
            },
        ),
    ]
