# Generated by Django 5.1.5 on 2026-07-18 07:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("attempt_number", models.PositiveIntegerField()),
                (
                    "college_id_image_url",
                    models.URLField(blank=True, default="", max_length=512),
                ),
                (
                    "gesture_selfie_image_url",
                    models.URLField(blank=True, default="", max_length=512),
                ),
                (
                    "gesture_type",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("RESUBMISSION_REQUIRED", "Resubmission required"),
                        ],
                        default="PENDING",
                        max_length=25,
                    ),
                ),
                ("review_notes", models.TextField(blank=True, default="")),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="users.user",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_requests",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "db_table": "verification_requests",
                "indexes": [
                    models.Index(fields=["status"], name="idx_verif_status"),
                    models.Index(
                        fields=["user", "-attempt_number"],
                        name="idx_verif_user_attempt",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "attempt_number"),
                        name="uniq_verification_attempt_per_user",
                    )
                ],
            },
        ),
    ]
