# Generated by Django 5.1.5 on 2026-07-15 02:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chats", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RevealIntent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PAID", "Paid"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual"),
                            ("CHAT_EXPIRED", "Chat expired"),
                        ],
                        default="MANUAL",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status_changed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reveal_intents",
                        to="chats.chat",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reveal_intents",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "db_table": "reveal_intents",
                "indexes": [models.Index(fields=["chat"], name="idx_reveal_chat")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("chat", "user"), name="uniq_reveal_intent_per_chat_user"
                    )
                ],
            },
        ),
    ]
