# Generated by Django 5.1.5 on 2026-09-27 09:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_chat_decision_deadline_at_alter_chat_end_reason'),
        ('reveal', '0001_initial'),
        ('users', '0002_alter_user_intent'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionRound',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger', models.CharField(choices=[('MID_CHAT', 'Mid chat'), ('EXPIRY', 'Expiry')], max_length=10)),
                ('phase', models.CharField(choices=[('DECISION', 'Decision'), ('PAYMENT', 'Payment'), ('SAFE_DECISION', 'Safe reveal decision'), ('RESOLVED', 'Resolved'), ('CANCELLED', 'Cancelled')], default='DECISION', max_length=15)),
                ('final_call', models.CharField(blank=True, choices=[('REVEAL', 'Reveal'), ('SAFE_REVEAL', 'Safe reveal'), ('EXTEND', 'Extend'), ('EXIT', 'Exit'), ('REVIEW', 'Review')], default='', max_length=12)),
                ('decision_deadline_at', models.DateTimeField(blank=True, null=True)),
                ('boy_revealed_to_girl_at', models.DateTimeField(blank=True, null=True)),
                ('safe_decision', models.CharField(choices=[('PENDING', 'Pending'), ('REVEAL_YOURSELF', 'Reveal yourself'), ('EXIT', 'Exit')], default='PENDING', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status_changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_rounds', to='chats.chat')),
            ],
            options={
                'db_table': 'decision_rounds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParticipantDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('choice', models.CharField(blank=True, choices=[('REVEAL', 'Reveal'), ('SAFE_REVEAL', 'Safe reveal'), ('EXTEND', 'Extend'), ('EXIT', 'Exit')], default='', max_length=12)),
                ('chosen_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('paid_with_coin', models.BooleanField(default=False)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='reveal.decisionround')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_decisions', to='users.user')),
            ],
            options={
                'db_table': 'participant_decisions',
            },
        ),
        migrations.DeleteModel(
            name='RevealIntent',
        ),
        migrations.AddIndex(
            model_name='decisionround',
            index=models.Index(fields=['chat', 'phase'], name='idx_round_chat_phase'),
        ),
        migrations.AddConstraint(
            model_name='participantdecision',
            constraint=models.UniqueConstraint(fields=('round', 'user'), name='uniq_decision_per_round_user'),
        ),
    ]
