# Generated by Django 5.1.5 on 2026-07-15 02:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("EXTENDED", "Extended"),
                            ("REVEALED", "Revealed"),
                            ("EXPIRED", "Expired"),
                            ("ENDED", "Ended"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                (
                    "current_phase",
                    models.CharField(
                        choices=[("ANONYMOUS", "Anonymous"), ("REVEALED", "Revealed")],
                        default="ANONYMOUS",
                        max_length=10,
                    ),
                ),
                (
                    "end_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EXPIRED", "Expired"),
                            ("USER_EXIT", "User exit"),
                            ("REPORT", "Report"),
                            ("REVEAL", "Reveal"),
                            ("SYSTEM", "System"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("current_phase_ends_at", models.DateTimeField(blank=True, null=True)),
                ("message_count", models.PositiveIntegerField(default=0)),
                (
                    "anonymous_chat_extension_count",
                    models.PositiveIntegerField(default=0),
                ),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "chats",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "current_phase_ends_at"],
                        name="idx_chat_status_phase_end",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ChatParticipant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("LEFT", "Left")],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("last_read_message_id", models.UUIDField(blank=True, null=True)),
                ("last_read_at", models.DateTimeField(blank=True, null=True)),
                ("is_chat_hidden", models.BooleanField(default=False)),
                ("hidden_at", models.DateTimeField(blank=True, null=True)),
                (
                    "joined_via",
                    models.CharField(
                        choices=[("MATCH", "Match")], default="MATCH", max_length=10
                    ),
                ),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="chats.chat",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_participations",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "db_table": "chat_participants",
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="idx_participant_user_status"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("chat", "user"), name="uniq_participant_per_chat_user"
                    )
                ],
            },
        ),
    ]
