# Generated by Django 5.1.5 on 2026-09-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='decision_deadline_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='end_reason',
            field=models.CharField(blank=True, choices=[('EXPIRED', 'Expired'), ('USER_EXIT', 'User exit'), ('AUTO_EXIT', 'Auto exit'), ('SAFE_REJECT', 'Safe reveal rejected'), ('REPORT', 'Report'), ('REVEAL', 'Reveal'), ('SYSTEM', 'System')], default='', max_length=15),
        ),
    ]
