# Generated by Django 5.1.5 on 2026-07-15 02:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chats", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("REVEAL", "Reveal"),
                            ("CHAT_EXTENSION", "Chat extension"),
                        ],
                        max_length=15,
                    ),
                ),
                ("amount_in_paise", models.PositiveIntegerField()),
                ("currency", models.CharField(default="INR", max_length=3)),
                (
                    "provider",
                    models.CharField(
                        choices=[("RAZORPAY", "Razorpay")],
                        default="RAZORPAY",
                        max_length=15,
                    ),
                ),
                (
                    "provider_order_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "provider_payment_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "provider_signature",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("REFUNDED", "Refunded"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "initiated_from",
                    models.CharField(
                        choices=[
                            ("CHAT_SCREEN", "Chat screen"),
                            ("CHAT_EXPIRED", "Chat expired"),
                        ],
                        max_length=15,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status_changed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="chats.chat",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "db_table": "payments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["chat", "purpose", "status"],
                        name="idx_payment_chat_purpose",
                    ),
                    models.Index(
                        fields=["user", "status"], name="idx_payment_user_status"
                    ),
                ],
            },
        ),
    ]
