# Generated by Django 5.1.5 on 2026-09-11 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('RAZORPAY', 'Razorpay'), ('GOOGLE_PLAY', 'Google Play')], default='RAZORPAY', max_length=15),
        ),
    ]
