# Generated by Django 5.1.5 on 2026-09-27 09:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_chat_decision_deadline_at_alter_chat_end_reason'),
        ('payments', '0002_alter_payment_provider'),
        ('users', '0002_alter_user_intent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='chats.chat'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='initiated_from',
            field=models.CharField(choices=[('CHAT_SCREEN', 'Chat screen'), ('CHAT_EXPIRED', 'Chat expired'), ('STORE', 'Store')], max_length=15),
        ),
        migrations.AlterField(
            model_name='payment',
            name='purpose',
            field=models.CharField(choices=[('REVEAL', 'Reveal'), ('SAFE_REVEAL', 'Safe reveal'), ('CHAT_EXTENSION', 'Chat extension'), ('CREDIT_PURCHASE', 'Credit purchase')], max_length=15),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reveal_coins', models.PositiveIntegerField(default=0)),
                ('safe_reveal_coins', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wallet', to='users.user')),
            ],
            options={
                'db_table': 'wallets',
            },
        ),
        migrations.CreateModel(
            name='CoinLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coin_type', models.CharField(choices=[('REVEAL', 'Reveal coin'), ('SAFE_REVEAL', 'Safe reveal coin')], max_length=15)),
                ('delta', models.IntegerField()),
                ('balance_after', models.PositiveIntegerField()),
                ('reason', models.CharField(choices=[('BUNDLE_PURCHASE', 'Bundle purchase'), ('CANCELLATION_CREDIT', 'Cancellation credit'), ('REVEAL_CONSUME', 'Reveal consume'), ('ADMIN_ADJUST', 'Admin adjust')], max_length=25)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coin_ledger', to='chats.chat')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coin_ledger', to='payments.payment')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger', to='payments.wallet')),
            ],
            options={
                'db_table': 'coin_ledger',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['wallet', 'coin_type'], name='idx_ledger_wallet_coin')],
            },
        ),
    ]
