# Generated by Django 5.1.5 on 2026-09-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_chat_alter_payment_initiated_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('GOOGLE_PLAY', 'Google Play')], default='GOOGLE_PLAY', max_length=15),
        ),
    ]
