# Generated by Django 5.1.5 on 2026-07-15 02:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("firebase_uid", models.CharField(max_length=128, unique=True)),
                ("college_email", models.EmailField(max_length=254, unique=True)),
                ("full_name", models.CharField(blank=True, default="", max_length=150)),
                (
                    "profile_photo_url",
                    models.URLField(blank=True, default="", max_length=512),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("OTHER", "Other"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "intent",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("RELATIONSHIP", "Relationship"),
                            ("FRIENDSHIP", "Friendship"),
                            ("CASUAL", "Casual"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("gender_preferences", models.JSONField(blank=True, default=list)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("RESUBMISSION_REQUIRED", "Resubmission required"),
                        ],
                        default="PENDING",
                        max_length=25,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "account_status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                            ("BANNED", "Banned"),
                            ("DELETED", "Deleted"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                (
                    "onboarding_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("last_active_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "users",
                "indexes": [
                    models.Index(
                        fields=["verification_status"], name="idx_user_verif_status"
                    ),
                    models.Index(
                        fields=["account_status"], name="idx_user_account_status"
                    ),
                ],
            },
        ),
    ]
