# Generated by Django 5.1.5 on 2026-09-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='intent',
            field=models.CharField(blank=True, choices=[('RELATIONSHIP', 'Relationship'), ('CASUAL', 'Casual')], default='', max_length=20),
        ),
    ]
