# Generated by Django 5.1.5 on 2026-10-02 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_intent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='intent',
            field=models.CharField(blank=True, choices=[('RELATIONSHIP', 'Relationship'), ('FRIENDSHIP', 'Friendship'), ('CASUAL', 'Casual')], default='', max_length=20),
        ),
    ]
