# Generated by Django 5.1.5 on 2026-10-02 07:28

import apps.users.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
        ('users', '0003_alter_user_intent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='college',
            field=models.ForeignKey(default=apps.users.models._default_college_id, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='colleges.college'),
        ),
    ]
