# Generated by Django 5.1.5 on 2026-07-15 02:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchQueue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "intent",
                    models.CharField(
                        choices=[
                            ("RELATIONSHIP", "Relationship"),
                            ("FRIENDSHIP", "Friendship"),
                            ("CASUAL", "Casual"),
                        ],
                        max_length=20,
                    ),
                ),
                ("gender_preferences", models.JSONField(blank=True, default=list)),
                (
                    "matchmaking_session_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SEARCHING", "Searching"),
                            ("CANCELLED", "Cancelled"),
                            ("TIMEOUT", "Timeout"),
                        ],
                        default="SEARCHING",
                        max_length=10,
                    ),
                ),
                ("joined_queue_at", models.DateTimeField(auto_now_add=True)),
                ("matched_at", models.DateTimeField(blank=True, null=True)),
                ("is_online", models.BooleanField(default=True)),
                ("last_heartbeat_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_queue_entries",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "db_table": "match_queue",
                "indexes": [
                    models.Index(
                        fields=["status", "intent", "joined_queue_at"],
                        name="idx_queue_status_intent",
                    ),
                    models.Index(
                        fields=["status", "last_heartbeat_at"],
                        name="idx_queue_status_heartbeat",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "SEARCHING")),
                        fields=("user",),
                        name="uniq_active_queue_entry_per_user",
                    )
                ],
            },
        ),
    ]
