# Generated by Django 5.1.5 on 2026-09-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchqueue',
            name='intent',
            field=models.CharField(choices=[('RELATIONSHIP', 'Relationship'), ('CASUAL', 'Casual')], max_length=20),
        ),
    ]
