# Generated by Django 5.1.5 on 2026-10-02 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0002_alter_matchqueue_intent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchqueue',
            name='intent',
            field=models.CharField(choices=[('RELATIONSHIP', 'Relationship'), ('FRIENDSHIP', 'Friendship'), ('CASUAL', 'Casual')], max_length=20),
        ),
    ]
