# Generated by Django 5.1.5 on 2026-10-02 07:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('allowed_email_domains', models.JSONField(blank=True, default=list)),
                ('launch_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'colleges',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LaunchNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('milestone', models.CharField(choices=[('T_MINUS_7D', '7 days before launch'), ('T_MINUS_1D', '1 day before launch'), ('T_MINUS_1H', '1 hour before launch'), ('LAUNCH', 'Launched')], max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='launch_notifications', to='colleges.college')),
            ],
            options={
                'db_table': 'launch_notifications',
                'constraints': [models.UniqueConstraint(fields=('college', 'milestone'), name='uniq_launch_notification')],
            },
        ),
    ]
