# Generated by Django 5.1.5 on 2026-07-15 02:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chats", "0001_initial"),
        ("messaging", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("HARASSMENT", "Harassment"),
                            ("ABUSE", "Abuse"),
                            ("SPAM", "Spam"),
                            ("FAKE_IDENTITY", "Fake identity"),
                            ("INAPPROPRIATE_CONTENT", "Inappropriate content"),
                            ("UNDERAGE", "Underage"),
                            ("OTHER", "Other"),
                        ],
                        max_length=25,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("UNDER_REVIEW", "Under review"),
                            ("RESOLVED", "Resolved"),
                            ("DISMISSED", "Dismissed"),
                        ],
                        default="OPEN",
                        max_length=15,
                    ),
                ),
                ("admin_notes", models.TextField(blank=True, default="")),
                (
                    "resolution_action",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("WARNING", "Warning"),
                            ("TEMP_SUSPENSION", "Temporary suspension"),
                            ("PERMANENT_BAN", "Permanent ban"),
                            ("CHAT_TERMINATED", "Chat terminated"),
                            ("NO_ACTION", "No action"),
                        ],
                        default="NONE",
                        max_length=20,
                    ),
                ),
                ("is_false_report", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status_changed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reports",
                        to="chats.chat",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reports_made",
                        to="users.user",
                    ),
                ),
                (
                    "reported_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="messaging.message",
                    ),
                ),
                (
                    "reported_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reports_received",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "db_table": "reports",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status"], name="idx_report_status"),
                    models.Index(
                        fields=["reported_user"], name="idx_report_reported_user"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("chat", "reported_by"),
                        name="uniq_report_per_chat_reporter",
                    )
                ],
            },
        ),
    ]
