# Generated by Django 5.1.5 on 2026-07-15 16:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("token", models.CharField(max_length=512, unique=True)),
                ("device_id", models.CharField(max_length=255)),
                (
                    "platform",
                    models.CharField(
                        choices=[("ANDROID", "Android"), ("IOS", "iOS")], max_length=10
                    ),
                ),
                (
                    "app_version",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "last_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_tokens",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "db_table": "device_tokens",
                "ordering": ["-last_seen_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"], name="idx_devicetoken_user_active"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "device_id"), name="uniq_device_per_user"
                    )
                ],
            },
        ),
    ]
